name: Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Tag name"
        required: true
        default: 'v2'
      buildCPU:
        description: "Build and push CPU image"
        type: boolean
        required: true
        default: true
      buildGPU:
        description: "Build and push GPU image"
        type: boolean
        required: true
        default: true
        
jobs:
  push_cpu_image_to_registry:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.buildCPU == 'true' }}

    name: Build docker CPU image and push to dockerhub

    steps:
      - name: Release space from worker
        run: |
          echo "Listing top largest packages"
          pkgs=$(dpkg-query -Wf '${Installed-Size}\t${Package}\t${Status}\n' | awk '$NF == "installed"{print $1 "\t" $2}' | sort -nr)
          head -n 30 <<< "${pkgs}"
          echo
          df -h
          echo
          sudo apt-get remove -y '^llvm-.*|^libllvm.*' || true
          sudo apt-get remove --auto-remove android-sdk-platform-tools || true
          sudo apt-get purge --auto-remove android-sdk-platform-tools || true
          sudo rm -rf /usr/local/lib/android
          sudo apt-get remove -y '^dotnet-.*|^aspnetcore-.*' || true
          sudo rm -rf /usr/share/dotnet
          sudo apt-get remove -y '^mono-.*' || true
          sudo apt-get remove -y '^ghc-.*' || true
          sudo apt-get remove -y '.*jdk.*|.*jre.*' || true
          sudo apt-get remove -y 'php.*' || true
          sudo apt-get remove -y hhvm powershell firefox monodoc-manual msbuild || true
          sudo apt-get remove -y '^google-.*' || true
          sudo apt-get remove -y azure-cli || true
          sudo apt-get remove -y '^mongo.*-.*|^postgresql-.*|^mysql-.*|^mssql-.*' || true
          sudo apt-get remove -y '^gfortran-.*' || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          echo
          echo "Listing top largest packages"
          pkgs=$(dpkg-query -Wf '${Installed-Size}\t${Package}\t${Status}\n' | awk '$NF == "installed"{print $1 "\t" $2}' | sort -nr)
          head -n 30 <<< "${pkgs}"
          echo
          sudo rm -rfv build || true
          df -h

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: './'
          no-cache: true
          file: 'Dockerfile'
          tags: luzfcb/aio-local-ai:${{ github.event.inputs.tagName }}
          provenance: false

  push_gpu_image_to_registry:
    runs-on: ubuntu-22.04
    environment: "DockerHubAccess"
    if: ${{ github.event.inputs.buildGPU == 'true' }}

    name: Build docker GPU image and push to dockerhub

    steps:
      - name: Available storage before
        run: df -h


      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
      - name: Available storage after
        run: df -h


      - name: Release space from worker
        run: |
          echo "Listing top largest packages"
          pkgs=$(dpkg-query -Wf '${Installed-Size}\t${Package}\t${Status}\n' | awk '$NF == "installed"{print $1 "\t" $2}' | sort -nr)
          head -n 50 <<< "${pkgs}"
          echo "Available storage before:"
          sudo df -h
          echo
          sudo apt-get remove -y '^llvm-.*|^libllvm.*' || true
          sudo apt-get remove --auto-remove android-sdk-platform-tools || true
          sudo apt-get purge --auto-remove android-sdk-platform-tools || true
          sudo rm -rf /usr/local/lib/android
          sudo apt-get purge -y '^dotnet-.*|^aspnetcore-.*' || true
          sudo apt-get purge -y '^temurin-.*|^ca-certificates-java.*' || true
          sudo apt-get purge -y '^libclang-.*' || true
          sudo rm -rf /usr/share/dotnet
          sudo apt-get purge -y '^mono-.*' || true
          sudo apt-get purge -y '^ghc-.*' || true
          sudo apt-get purge -y '.*jdk.*|.*jre.*' || true
          sudo apt-get purge -y 'php.*' || true
          sudo apt-get purge -y hhvm powershell firefox monodoc-manual msbuild || true
          sudo apt-get purge -y '^google-.*' || true
          sudo apt-get purge -y azure-cli || true
          sudo apt-get purge -y '^mongo.*-.*|^postgresql-.*|^mysql-.*|^mssql-.*' || true
          sudo apt-get purge -y '^gfortran-.*' || true
          sudo apt-get purge -y '^microsoft-edge-stable.*|^firefox.*|powershell.*' || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          echo
          echo "Listing top largest packages"
          pkgs=$(dpkg-query -Wf '${Installed-Size}\t${Package}\t${Status}\n' | awk '$NF == "installed"{print $1 "\t" $2}' | sort -nr)
          head -n 50 <<< "${pkgs}"
          echo
          sudo rm -rfv build || true
          sudo docker system prune --all --volumes --force || true
          echo "Available storage after:"
          df -h

      - name: Available storage after
        run: df -h

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Available storage before build
        run: df -h

      - name: Extract Base GPU Docker Image name
        id: extract-image
        run: |
          BASE_GPU_IMAGE=$(awk '/^FROM / {print $2}' Dockerfile.cuda12)
          echo "Base GPU image found: $BASE_GPU_IMAGE"
          echo "BASE_GPU_IMAGE=$BASE_GPU_IMAGE" >> $GITHUB_ENV

      - name: Pull Base Docker Image
        run: |
          echo "Pulling Docker image: $BASE_GPU_IMAGE"
          docker pull "$BASE_GPU_IMAGE"
        env:
          BASE_IMAGE: ${{ env.BASE_GPU_IMAGE }}

      - name: Create a TMPDIR for docker build on a different disk
        run: |
          mkdir -p /tmp/docker-build
          export TMPDIR=/tmp/docker-build
          echo "TMPDIR=$TMPDIR" >> $GITHUB_ENV
          
      - name: Available storage before build
        run: df -h

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: linux/amd64
          context: './'
          file: 'Dockerfile.cuda12'
          tags: luzfcb/aio-local-ai-cuda12:${{ github.event.inputs.tagName }}
          provenance: false
        env:
          TMPDIR: ${{ env.TMPDIR }}

      - name: Verify Docker image size
        uses: luzfcb/docker-image-size-limit@master
        with:
          image: "luzfcb/aio-local-ai-cuda12:${{ github.event.inputs.tagName }}"
          size: "47GB"
          show_current_size: true
          dry_run: true

      - name: Available storage after build
        run: df -h

      - name: Push container image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          context: './'
          file: 'Dockerfile.cuda12'
          tags: luzfcb/aio-local-ai-cuda12:${{ github.event.inputs.tagName }}
          provenance: false
